[workspace]
channels = ["conda-forge", "bioconda"]
name = "CircNetVis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-shiny = ">=1.11.1,<2"
r-gplots = ">=3.2.0,<4"
r-visnetwork = ">=2.1.4,<3"
r-shinythemes = ">=1.2.0,<2"
r-shinyjs = ">=2.1.0,<3"
r-dt = ">=0.34.0,<0.35"
r-doparallel = ">=1.0.17,<2"
r-rjson = ">=0.2.23,<0.3"
r-rsqlite = ">=2.4.3,<3"
r-dbplyr = ">=2.5.1,<3"
r-dbi = ">=1.2.3,<2"
r-dplyr = ">=1.1.4,<2"
"r-data.table" = ">=1.17.8,<2"
bioconductor-biostrings = { version = ">=2.74.0,<3", channel = "bioconda" }
r-markdown = ">=2.0,<3"
bioconductor-genomeinfodb = { version = ">=1.42.0,<2", channel = "bioconda" }
